/*
This file was generated by BMPload.exe from Reach Technology on Tue Nov 14 19:41:06 2017
 from the file C:\CMPE240\git\macros.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define display_settings 1
#define display_main 2
#define display_service 3
#define display_temperature 4
#define Splash 5
