/*
This file was generated by BMPload.exe from Reach Technology on Tue Oct 10 19:07:14 2017
 from the file C:\CMPE240\macros.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define display_page1 1
#define display_home 2
