/*
This file was generated by BMPload.exe from Reach Technology on Sat Nov 25 11:51:48 2017
 from the file C:\CMPE240\git\macros.mac

This file displays each macro name with its assigned macro number.

Include this file in the host control program.
*/

#define display_settings 1
#define display_service 2
#define display_temperature 3
#define Splash 4
#define display_settings_new 5
#define display_configuration 6
